---
title: "Skitouring"
author: "Kaspar Rufibach"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output:
  html_document:
    keep_md: true
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  github_document: 
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "lubridate", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- "C:/rufibach/01 personal/05_sport/touren/"
path <- paste(getwd(), "/", sep = "")

## =================================================================
## input data
## =================================================================
touren <- read_excel(paste(path, "data/touren.xls", sep = ""))

all <- touren %>% mutate(date = as.Date(date, origin = "1899-12-30"), begleitung1 = NULL, begleitung2 = NULL, region = NULL, kommentar = NULL) %>% 
  arrange(sport, start, end, time) %>% filter(sport == "Skitour")
all[is.na(all)] <- ""
```

# Summary over years

List by far not complete. Multiple tours within same month are pooled and frequency is given.

```{r, echo = FALSE, results = 'asis', message = FALSE, eval = FALSE}
with(subset(touren, sport == "Skitour"), pander(addmargins(table(as.character(end), year(date))), digits = 1))
```

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
par(mfrow = c(1, 1), las = 2, mar = c(4, 8, 1, 1))

ski <- (touren %>% filter(sport == "Skitour") %>% select(start, end, date, time))
tour <- unique(ski$end)

# x-axis
xs <- ymd_hms(paste(min(year(ski$date)):max(year(ski$date) + 1), "0101 00:00:00", sep = ""))
plot(xs, rep(0, length(xs)), type = "n", ylim = c(0, length(tour)), xaxt = "n", yaxt = "n", xlab = "", ylab = "")
axis(1, at = xs, labels = year(xs))
axis(2, at = 1:length(tour), labels = tour)
abline(h = 1:length(tour), lty = 2, col = grey(0.5))
offset <- 0.2

for (i in 1:length(tour)){
  dat.i <- (ski %>% filter(end == tour[i]) %>% arrange(date) %>% group_by("w" = paste(year(date), month(date), sep = "")) %>% add_tally() %>% slice(1))
  text(dat.i$date, rep(i, nrow(dat.i)), dat.i$n)
}
```

# Listing, chronologically and by time

For listings by time, tours with missing time are omitted.

```{r, include=FALSE}
i <- 1
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 2
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 3
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 4
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 5
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 6
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 7
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 8
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 9
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 10
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 11
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 12
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 13
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 14
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 15
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 16
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 17
```

```{r test-main, child = 'tour_summary.Rmd'}
```



