---
title: "Hikes, runs, and rides"
author: "Kaspar Rufibach"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output:
  html_document:
    keep_md: true
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  github_document: 
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- paste(getwd(), "/", sep = "")

## =================================================================
## input touren data
## =================================================================
suppressWarnings(touren <- as.data.frame(read_excel(paste(path, "data/touren.xls", sep = ""), 
                     sheet = "all",
                     col_types = c(rep("text", 4),      # 
                                   rep("numeric", 1),       # 
                                   rep("text", 4)
                     ))))

all0 <- touren %>% mutate(date = as.Date(date, origin = "1899-12-30"), begleitung1 = NULL, begleitung2 = NULL, region = NULL, kommentar = NULL) %>% 
  arrange(sport, start, end, time)
all0[is.na(all0)] <- ""
```

# Bike

For listings by time, tours with missing time are omitted.

```{r, include=FALSE}
all <- (all0 %>% filter(sport == "Bike"))
tour <- unique(all$end)
```

```{r, include=FALSE}
i <- 1
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 2
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 3
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 4
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 5
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 6
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 7
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 8
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 9
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 10
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 11
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 12
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 13
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 14
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 15
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 16
```

# Run

```{r, include=FALSE}
all <- (all0 %>% filter(sport == "Run"))
tour <- unique(all$end)
```

```{r, include=FALSE}
i <- 1
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 2
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 3
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 4
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 5
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 6
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 7
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 8
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 9
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 10
```

# Hike

```{r, include=FALSE}
all <- (all0 %>% filter(sport == "Hike"))
tour <- unique(all$end)
```

```{r, include=FALSE}
i <- 1
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 2
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 3
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 4
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 5
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 6
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 7
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 8
```

```{r test-main, child = 'tour_summary.Rmd'}
```

```{r, include=FALSE}
i <- 9
```

