---
title: "Clinical biostatistics at Roche"
author: "Kaspar Rufibach"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output:
  html_document:
    keep_md: true
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  github_document: 
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "dplyr", "readxl", "ggplot2", "lubridate", "tidyr")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
```

# Department of Biostatistics, F. Hoffmann-La Roche

The Department of Biostatistics has about 220 statisticians located in Basel (Switzerland), Welwyn (UK), South San Francisco (US), Mississauga (CA), and Shanghai. The vision of the department is:

**Bringing data to life to accelerate innovation across Roche**

[Biostatistics leadership team on this vision](https://www.youtube.com/watch?v=KeA3e7z7E9Q&authuser=0)

[Poster that was presented at an internal career development day, outlining what we do](data/20180918_DataScienceCareerDay_Biometrics_BioStats.pptx)

## Methods, Collaboration, and Outreach Group (MCO)

MCO is a group within the Department of Biostatistics, currently consisting of the head and four full-time permanent members (one of which is [Kaspar Rufibach](http://www.kasparrufibach.ch)). 

The broad remit of the group is to support the clinical biostatisticians in their daily work, through consulting, methods development, collaboration and outreach activities (e.g. in X-pharma working groups, supervision of students, collaboration with academics or regulators, etc). Typically, members of the group have broad experience in applied and clinical biostatistics. 

# Jobs at Roche

[Roche job portal](https://www.roche.com/careers/jobs/jobsearch.htm)

Search for "statistics" and "biostatistics".

# Internships within Roche biostatistics in Basel

We have about four internship every year in Basel. Those for 2020 are announced [here](https://tinyurl.com/biostats-roche-basel).

Note that in Basel, we only hire students who are currently enrolled at University at typically studying towards an MSc or PhD degree. We do not hire graduates for internships. If you have already graduated I invite you to apply for regular jobs under the portal linked above.

# Tips

If you'd like to work as a statistician in pharma, consider the following:

 + There are many opportunities for quantitatively trained people in pharma, the work as a clinical biostatistician just being one of them.
 + It is not easy to get into pharma. Many of those now working in pharma applied more than once, and maybe also started their career elsewhere, e.g. in a clinical research organization (CRO).
 + The advantage of a large company is that you can "change job" within the company. So, if it is difficult to land a job where you would like to end up, start somewhere else and then move within the company.
 + A lot relies on being known. To increase your visibility consider attending or presenting at conferences, [BBS seminars](http://bbs.ceb-institute.org/), talk to people working where you would like to work, ...

