---
title: "Hikes, runs, and rides"
author: "Kaspar Rufibach"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output:
  html_document:
    keep_md: true
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  github_document: 
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- paste(getwd(), "/", sep = "")

## =================================================================
## input touren data
## =================================================================
suppressWarnings(touren <- as.data.frame(read_excel(paste(path, "data/touren.xls", sep = ""), 
                     sheet = "all",
                     col_types = c(rep("text", 4),      # 
                                     rep("numeric", 1),       # 
                                     rep("text", 4)
                     ))))

all <- touren %>% mutate(date = as.Date(date, origin = "1899-12-30"), begleitung1 = NULL, begleitung2 = NULL, region = NULL, kommentar = NULL) %>% 
  arrange(sport, start, end, time)
all[is.na(all)] <- ""
```


# Bike

```{r, echo = FALSE, results = 'asis', message = FALSE}
pander(all %>% filter(sport == "Bike")) 
```


# Run

```{r, echo = FALSE, results = 'asis', message = FALSE}
pander(all %>% filter(sport == "Run")) 
```


# Hike

```{r, echo = FALSE, results = 'asis', message = FALSE}
pander(all %>% filter(sport == "Hike")) 
```

# Skitour

```{r, echo = FALSE, results = 'asis', message = FALSE}
pander(all %>% filter(sport == "Skitour")) 
```
