---
title: "Countries visited"
author: "Kaspar Rufibach"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output:
  html_document:
    keep_md: true
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  github_document: 
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "dplyr", "readxl", "ggplot2", "lubridate", "tidyr")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- paste(getwd(), "/", sep = "")

#source(paste(path, "functions/plotSummary.r", sep = ""))

## =================================================================
## input 
## =================================================================
countries <- as.data.frame(read_excel(paste(path, "data/countries.xlsx", sep = ""), col_types = NULL))
countries <- (countries %>% mutate("year" = year(month)))

countries <- countries %>% pivot_longer(cols = US:Belgium, names_to = "country", values_to = "days")
countries2 <- countries %>%
  group_by(year, country) %>%
    summarise(days = sum(days, na.rm = TRUE)) 

#print(countries2, n = 40)

countries3 <- countries %>%
  group_by(year) %>%
    summarise(days = sum(days, na.rm = TRUE)) 
```

# Per year and country

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 9}
ggplot(countries2, aes(fill = country, y = days, x = country)) + 
  geom_bar(position="dodge", stat="identity") +
  ggtitle("Travel") +
  facet_wrap(~year) +
#  theme_ipsum() 
  theme(legend.position = "none") +
  xlab("") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_text(aes(label = days), vjust = 1.6, color = "white", size = 3.5) + 
  theme(text = element_text(size = 20))
```

# Per year

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 4.5}
ggplot(countries3, aes(fill = year, y = days, x = year)) + 
  geom_bar(position="dodge", stat="identity") +
  ggtitle("Travel") +
#  facet_wrap(~year) +
#  theme_ipsum() 
  theme(legend.position = "none") +
  xlab("") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_text(aes(label = days), vjust = 1.6, color = "white", size = 3.5) +
  theme_minimal() + 
  theme(text = element_text(size = 20))
```
