---
title: "Yearly summaries"
author: "Kaspar Rufibach"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`, as per 12th August'
output:
  html_document:
    keep_md: true
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  github_document: 
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl", "ggplot2")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- paste(getwd(), "/", sep = "")

source(paste(path, "functions/plotSummary.r", sep = ""))

## =================================================================
## input 
## =================================================================
sportKR <- as.data.frame(read_excel(paste(path, "data/zsf.xlsx", sep = ""), col_types = NULL))
sportKR <- (sportKR %>% mutate("Sport" = as.factor(Sport), "Einheit" = as.factor(Einheit)))

lastcol <- ncol(sportKR)

# define which years to include
include <- sportKR[sportKR[, "Sport"] == "Include", 3:ncol(sportKR)]
include <- as.numeric(include) * (3:ncol(sportKR))
include <- include[include > 0] 

# collapse certain disciplines
sportKR[sportKR[, "Sport"] == "Bike", 3:ncol(sportKR)] <- sportKR[sportKR[, "Sport"] == "Bike", 3:ncol(sportKR)] + sportKR[sportKR[, "Sport"] == "Velo", 3:ncol(sportKR)] 

sportKR[sportKR[, "Sport"] == "Running", 3:ncol(sportKR)] <- sportKR[sportKR[, "Sport"] == "Running", 3:ncol(sportKR)] + sportKR[sportKR[, "Sport"] == "Trail Running", 3:ncol(sportKR)] 

# remove unused rows
sportKR <- (sportKR %>% filter(!(Sport %in% c("Include", "Velo", "Trail Running"))))

# linearly extrapolate last column to full year
toda <- Sys.Date()
first <- as.Date(paste(substr(toda, 1, 4), "-01-01", sep = ""))
frac <- as.numeric((toda - first) / 365.25)
sportKR[, lastcol] <- sportKR[, lastcol] / frac

dat <- sportKR[, 3:lastcol]

# only use years defined by "include"
sportKR <- sportKR[, c(1, 2, include)]
dat <- dat[, include - 2]

# choose scaling
skal <- c(1, 52)
skal.nam <- c(" per year", " per week")
```

Numbers for `r tail(colnames(dat), 1)` are linearly extrapolated from `r toda` to the full year.

# Yearly summaries

## Kilometer

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
par(mfrow = c(1, 1), mar = c(3.5, 4.5, 3, 1), las = 2)
km <- subset(sportKR, Einheit == "Km")
xs <- as.numeric(colnames(km)[3:ncol(km)])
ys <- km[, 3:ncol(km)]
plot(0, 0, type = "n", xlim = range(xs), ylim = c(0, max(ys)), xlab = "", ylab = "Kilometer", 
     main = "Kilometer")
for (i in 1:nrow(km)){lines(xs, ys[i, ], type = "b", col = i + 1, lwd = 2)}
legend("bottomleft", legend = km$Sport, lty = 1, col = 2:(nrow(km) + 1), bty = "n", lwd = 2)
```

## Elevation gain

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
par(mfrow = c(1, 1), mar = c(3.5, 5, 3, 1), las = 2)
km <- subset(sportKR, Einheit == "Hm")
xs <- as.numeric(colnames(km)[3:ncol(km)])
ys <- km[, 3:ncol(km)]
plot(0, 0, type = "n", xlim = range(xs), ylim = c(0, max(ys)), xlab = "", ylab = "", 
     main = "Elevation gain")
for (i in 1:nrow(km)){lines(xs, ys[i, ], type = "b", col = i + 1, lwd = 2)}
legend("topleft", legend = km$Sport, lty = 1, col = 2:(nrow(km) + 1), bty = "n", lwd = 2)

par(las = 0)
mtext(text = "Elevation gain", side = 2, line = 4, adj = 0.5)
```

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
df <- rbind(cbind(xs, t(ys)[, 1]), cbind(xs, t(ys)[, 2]), cbind(xs, t(ys)[, 3]))
df <- data.frame(df, rep(as.character(km[, "Sport"]), each = length(xs)))
colnames(df) <- c("Jahr", "Hm", "Disziplin")
ggplot(df, aes(x = Jahr, y = Hm, fill = Disziplin)) + geom_area(position = 'stack')
```

## Time

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
par(mfrow = c(1, 1), mar = c(3.5, 4.5, 3, 1), las = 2)
km <- subset(sportKR, Einheit == "Time")
xs <- as.numeric(colnames(km)[3:ncol(km)])
ys <- km[, 3:ncol(km)]
plot(0, 0, type = "n", xlim = range(xs), ylim = c(0, max(ys)), xlab = "", ylab = "Stunden", 
     main = "Stunden")
for (i in 1:nrow(km)){lines(xs, ys[i, ], type = "b", col = i + 1, lwd = 2)}
legend("topleft", legend = km$Sport, lty = 1, col = 2:(nrow(km) + 1), bty = "n", lwd = 2)
```

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
df <- rbind(cbind(xs, t(ys)[, 1]), cbind(xs, t(ys)[, 2]), cbind(xs, t(ys)[, 3]))
df <- data.frame(df, rep(as.character(km[, "Sport"]), each = length(xs)))
colnames(df) <- c("Jahr", "Time", "Disziplin")
ggplot(df, aes(x = Jahr, y = Time, fill = Disziplin)) + geom_area(position = 'stack')
```

## Places

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 7}
par(mfrow = c(1, 1), mar = c(3.5, 4.5, 3, 1), las = 2)
km <- subset(sportKR, Einheit == "Number" & (Sport %in% c("Exersuisse")) == FALSE)
xs <- as.numeric(colnames(km)[3:ncol(km)])
ys <- km[, 3:ncol(km)]
plot(0, 0, type = "n", xlim = range(xs), ylim = c(0, max(ys)), xlab = "", ylab = "number", 
     main = "Number")
for (i in 1:nrow(km)){lines(xs, ys[i, ], type = "b", col = i + 1, lwd = 2)}
legend("topleft", legend = km$Sport, lty = 1, col = 2:(nrow(km) + 1), bty = "n", lwd = 2)
```

# Summary over winter seasons (not years)

## Skiing

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 7}
par(mfrow = c(1, 1), mar = c(6, 4.5, 3, 1), las = 2)
km <- subset(sportKR, Einheit == "Number" & (Sport %in% c("Skiing", "Skitouring")) == TRUE)
xs <- as.numeric(colnames(km)[3:ncol(km)])
ys <- km[, 3:ncol(km)]
plot(0, 0, type = "n", xlim = range(xs), ylim = c(0, max(ys)), xlab = "", ylab = "number", 
     main = "Number", xaxt = "n")
axis(1, at = xs, labels = paste(xs - 1, " / ", xs, sep = ""))
for (i in 1:nrow(km)){lines(xs, ys[i, ], type = "b", col = i + 1, lwd = 2)}
legend(2013.5, 20, legend = km$Sport, lty = 1, col = 2:(nrow(km) + 1), bty = "n", lwd = 2)
```

# Activity per year

Shaded red bars are linearly extrapolated from `r toda` to the entire year.

## Bike

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
s <- 1
for (i in 1:3){plotSummary(dat = dat, sportKR = sportKR, i = i, s = s)}
```

## Run

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
for (i in 4:6){plotSummary(dat = dat, sportKR = sportKR, i = i, s = s)}
```

## Hiking

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
for (i in 7:9){plotSummary(dat = dat, sportKR = sportKR, i = i, s = s)}
```

## Exersuisse

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
for (i in 10){plotSummary(dat = dat, sportKR = sportKR, i = i, s = s)}
```


## Orte

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
for (i in 13:nrow(dat)){plotSummary(dat = dat, sportKR = sportKR, i = i, s = s)}
```

# Activity per week

## Bike

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
s <- 2
par(mar = c(4, 4, 4, 1), las = 1)
for (i in 1:3){plotSummary(dat = dat, sportKR = sportKR, i = i, s = s)}
```

## Run

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
for (i in 4:6){plotSummary(dat = dat, sportKR = sportKR, i = i, s = s)}
```

## Hiking

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
for (i in 7:9){plotSummary(dat = dat, sportKR = sportKR, i = i, s = s)}
```

## Exersuisse

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
for (i in 10){plotSummary(dat = dat, sportKR = sportKR, i = i, s = s)}
```

