---
title: "Wettkaempfe"
author: "Kaspar Rufibach"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "lubridate")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- "C:/rufibach/01 personal/sport/wettkaempfe/"

## =================================================================
## input uebu data
## =================================================================
wett_in <- read.csv(paste(path, "wettkaempfe.csv" , sep = ''), sep = ";", as.is = TRUE)
wett <- subset(wett_in, Alexander == 0 & Lorenz == 0)

# order by decreasing frequency of participation
Anlass <- wett[ ,"Anlass"]
wett <- merge(wett, table(Anlass), by = "Anlass")
wett <- wett[with(wett, rev(order(Freq, -Jahr))), ]

Anlass    <- wett[ ,"Anlass"]
Disziplin <- wett[ ,"Disziplin"]
Distanz   <- wett[ ,"Distanz"]
Jahr      <- wett[ ,"Jahr"]
Nr        <- wett[ ,"Nr"]
Block     <- wett[ ,"Block"]
Zeit      <- hms(wett[, "Zeit"], quiet = TRUE)
Kat_Rang  <- wett[ ,"Kat_Rang"]
Kat_Teiln <- wett[ ,"Kat_Teiln"]
M_Rang    <- wett[ ,"M_Rang"]
M_Teiln   <- wett[ ,"M_Teiln"]
Gewicht   <- wett[ ,"Gewicht"]
Kommentar <- wett[ ,"Kommentar"]

# min/km
minkm <- round(as.period(as.period(Zeit, unit = "sec") / Distanz * 1000, unit = "min"), 1)

# time trafo function
s <- seconds(Zeit)[1]
```


# Anzahl Teilnahmen pro Anlass

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 7}
par(mfrow = c(1, 1), las = 2, mar = c(19, 3, 1, 1))
a <- table(Anlass)
a <- a[rev(order(a))]
barplot(a)
abline(h = 1:100, col = grey(0.5), lty = 2)
```

# Anzahl Teilnahmen pro Jahr und Disziplin

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
par(mfrow = c(1, 1), las = 2, mar = c(4.5, 3, 1, 1))
b <- table(Disziplin, Jahr)
barplot(b, beside = TRUE, legend = TRUE, args.legend = list("bty" = "n", "x" = "topleft"))
abline(h = 1:100, col = grey(0.5), lty = 2)
```

Bis jetzt habe ich an `r sum(Disziplin == "Run")` Laeufen und `r sum(Disziplin == "Bike")` Bikerennen teilgenommen.


# Alle Laeufe

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 3.5}
# ypos
ypos <- seq(0, 14100, by = 300)

# ylabs
h1 <- paste("0H ", seq(0, 55, by = 5), "M 00.0S")
h2 <- paste("1H ", seq(0, 55, by = 5), "M 00.0S")
h3 <- paste("2H ", seq(0, 55, by = 5), "M 00.0S")
h4 <- paste("3H ", seq(0, 55, by = 5), "M 00.0S")
ylab <- hms(c(h1, h2, h3, h4))

# Konstruktion achsenbeschriftung:  
# a <- hms("1H 00M 00.0S")
# seconds(a)

for (i in 1:length(a)){
    cat(paste(names(a)[i], "\n", sep = "")) 
    ind <- (Anlass == names(a)[i])

    if (all(is.na(Zeit[ind])) == FALSE){
           
          par(mfrow = c(1, 1), mar = c(3.5, 6, 3, 1), las = 2)
          plot(Jahr[ind], as.numeric(Zeit[ind]), type = "p", pch = 1, 
               main = names(a)[i], yaxt = "n",
               xlab = "", ylab = "", col = 2, ylim = c(3600, 7200))
          axis(2, at = ypos, labels = as.character(ylab))
          
          }
    cat("\n")  
} # end i
```
