---
title: "Skitouren"
author: "Kaspar Rufibach"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "lubridate", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- "C:/rufibach/01_personal/05_sport/touren/"

## =================================================================
## input uebu data
## =================================================================
dat <- read_excel(paste(path, "touren.xls", sep = ""))

sport   <- dat[ ,"sport"]
region  <- dat[ ,"region"]
start   <- dat[ ,"start"]
end     <- dat[ ,"end"]
date    <- dat[ ,"date"]
time    <- hms(as.vector(apply(dat[ ,"time"], 1:2, as.character)), quiet = TRUE)
begleitung1 <- dat[ ,"begleitung1"]
begleitung2 <- dat[ ,"begleitung2"]

Jahr0 <- year(as.data.frame(dat)[, "date"])
```

# Skitouren

Liste leider bei weitem nicht vollst?ndig.


```{r, echo = FALSE, results = 'asis', message = FALSE, eval = FALSE}
with(subset(dat, sport == "Skitour"), pander(addmargins(table(as.character(end), year(date))), digits = 1))
```



```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 5}
par(mfrow = c(1, 1), las = 2, mar = c(4, 8, 1, 1))
Anlass <- subset(end, sport == "Skitour")[[1]]
Jahr <- subset(Jahr0, sport == "Skitour")
a <- table(Anlass)
a <- a[rev(order(a))]
ys <- length(a):1
uJ <- sort(unique(Jahr))

plot(0, 0, type = "n", xlim = range(Jahr), ylim = c(-1, length(unique(Anlass))), xaxt = "n", xlab = "", ylab = "", yaxt = "n")
axis(1, at = uJ, labels = uJ)
axis(2, at = ys, labels = names(a))
abline(h = 1:100, lty = 3, col = grey(0.5))

for (i in 1:length(uJ)){
  Anlass_i <- Anlass[Jahr == uJ[i]]
    for (j in 1:length(unique(Anlass_i))){
     ind <- (Anlass_i[j] == names(a))
     xs <- uJ[i]
     ys_j <- ys[ind]
     text(xs, ys_j, col = i, labels = sum(unique(Anlass_i)[j] == Anlass_i), cex = 1.5)
    }
}


for (i in 1:length(uJ)){text(uJ[i], -1, sum(Jahr == uJ[i]))}
```
